import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.concurrent.TimeUnit
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.ValueSource
import org.gradle.api.provider.ValueSourceParameters
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.shadow)
    id ("org.sonarqube") version "7.5.0.8588"
    application
    jacoco
}

group = "com.jitunicornfx.insightidr"
version = "0.3.1"

// ---------------------------------------------------------------------------
// Build-time server identity
//
// `version` above is the single source of truth. This task bakes it — plus the git commit the build
// came from — into a resource that BuildInfo.kt reads at runtime, so the version reported by
// insightidr_server_info, the MCP Implementation block, the update comparison, the outbound
// User-Agent and the spool manifest can never drift from the build that produced them.
// ---------------------------------------------------------------------------

/**
 * Runs a git command and returns its trimmed stdout, or "" for ANY failure: git not installed, not a
 * git checkout, a non-zero exit, or a process that hangs. A missing SHA must never fail the build.
 *
 * A ValueSource rather than a configuration-time exec, so this stays correct if the configuration
 * cache is ever enabled.
 */
abstract class GitOutput : ValueSource<String, GitOutput.Params> {
    interface Params : ValueSourceParameters {
        val projectDir: DirectoryProperty
        val args: ListProperty<String>
    }

    override fun obtain(): String = runCatching {
        val process = ProcessBuilder(listOf("git") + parameters.args.get())
            .directory(parameters.projectDir.get().asFile)
            .redirectError(ProcessBuilder.Redirect.DISCARD)
            .start()
        val stdout = process.inputStream.bufferedReader().readText()
        if (!process.waitFor(10, TimeUnit.SECONDS)) {
            process.destroyForcibly()
            ""
        } else if (process.exitValue() == 0) {
            stdout.trim()
        } else {
            ""
        }
    }.getOrDefault("")
}

fun gitOutput(vararg args: String): Provider<String> =
    providers.of(GitOutput::class.java) {
        parameters.projectDir.set(layout.projectDirectory)
        parameters.args.set(args.toList())
    }

// Deliberately not `git describe`: it needs tags and fails on a shallow CI clone.
val gitSha: Provider<String> = gitOutput("rev-parse", "--short=12", "HEAD")
val gitCommitTime: Provider<String> = gitOutput("log", "-1", "--format=%cI")
val gitStatus: Provider<String> = gitOutput("status", "--porcelain", "--untracked-files=no")

// An empty status also means "no git at all", so only claim dirtiness when there IS a SHA.
val gitDirty: Provider<Boolean> = provider { gitSha.get().isNotEmpty() && gitStatus.get().isNotBlank() }

val generateBuildInfo = tasks.register("generateBuildInfo") {
    group = "build"
    description = "Writes the build-time server identity resource read by BuildInfo.kt."

    val projectVersion = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/resources/buildinfo")

    // These four are the ONLY declared inputs, and every one of them is stable across an ordinary
    // rebuild. The generation timestamp written below is deliberately NOT an input: a wall clock as
    // an input would leave this task — and therefore processResources, jar, shadowJar and test —
    // out of date on every single build, turning every build into a full build.
    inputs.property("version", projectVersion)
    inputs.property("gitSha", gitSha)
    inputs.property("gitCommitTime", gitCommitTime)
    inputs.property("gitDirty", gitDirty)
    outputs.dir(outputDir)

    // Capture providers, never `project`, so the action stays configuration-cache safe.
    val sha = gitSha
    val commitTime = gitCommitTime
    val dirty = gitDirty

    doLast {
        val target = outputDir.get().asFile.resolve("META-INF").apply { mkdirs() }
            .resolve("insightidr-mcp-build.properties")
        // Hand-written rather than Properties.store(), which prepends a "#<date>" comment and would
        // put a wall clock into the bytes unconditionally. Every value is drawn from [0-9A-Za-z.:+-]
        // only, so no .properties escaping is needed; BuildInfo re-validates on the way in anyway.
        target.writeText(
            buildString {
                appendLine("# Generated by :generateBuildInfo - do not edit.")
                appendLine("version=$projectVersion")
                sha.get().takeIf { it.isNotEmpty() }?.let { appendLine("git.sha=$it") }
                commitTime.get().takeIf { it.isNotEmpty() }?.let { appendLine("git.commitTime=$it") }
                appendLine("git.dirty=${dirty.get()}")
                appendLine("build.generatedAt=" + Instant.now().truncatedTo(ChronoUnit.SECONDS))
            },
            Charsets.UTF_8,
        )
    }
}

sourceSets.named("main") {
    // Passing the TaskProvider (not a bare path) carries the task dependency, so processResources,
    // jar, shadowJar, `run` and `test` all see the resource without an explicit dependsOn.
    resources.srcDir(generateBuildInfo)
}

dependencies {
    implementation(platform(libs.ktor.bom))

    implementation(libs.mcp.kotlin.server)

    // Command-line interface.
    implementation(libs.clikt)

    // HTTP client used to talk to the InsightIDR REST API. OkHttp (blocking sockets, its own thread
    // pool) rather than CIO: CIO's NIO selector opens a loopback self-pipe (an AF_UNIX socket on
    // recent JDKs) that some locked-down Windows/EDR hosts refuse, crashing the HTTP layer at startup.
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.okhttp)

    // Only required for the optional --http (Streamable HTTP / SSE) transport.
    implementation(libs.ktor.server.cio)
    implementation(libs.ktor.server.cors)

    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.core)

    // slf4j-simple logs to stderr by default, which keeps stdout clean for the
    // MCP JSON-RPC channel when running over stdio.
    implementation(libs.slf4j.simple)

    testImplementation(kotlin("test"))
    testImplementation(libs.mcp.kotlin.client)

    // Ktor MockEngine lets tests drive the tool handlers without real network calls.
    testImplementation(libs.ktor.client.mock)
    // testApplication drives the --http transport guard end to end without binding a socket.
    testImplementation(libs.ktor.server.test.host)

    // JUnit Platform engine so `useJUnitPlatform()` can actually discover and run tests.
    // JUnit 6 unifies platform/jupiter/vintage under one 6.x version (baseline Java 17+).
    testImplementation(platform("org.junit:junit-bom:6.1.3"))
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")
    // Pin the launcher to the same 6.x line so Gradle's test worker matches the engine.
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

}

application {
    mainClass.set("com.jitunicornfx.insightidr.mcp.MainKt")
}

kotlin {
    compilerOptions {
        jvmTarget = JvmTarget.JVM_21
        javaParameters = true
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.test {
    useJUnitPlatform()
    // Always refresh the coverage report after the tests run.
    finalizedBy(tasks.jacocoTestReport)
}

jacoco {
    // 0.8.15+ is required to instrument/run under recent JDKs (this project builds on JDK 21+).
    toolVersion = "0.8.15"
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)
    reports {
        xml.required.set(true)   // machine-readable; consumed by SonarQube
        html.required.set(true)  // human-readable report
        csv.required.set(false)
    }
}

// Optional coverage gate. Raise `minimum` once tests exist to fail the build below a threshold.
tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                counter = "LINE"
                minimum = "0.00".toBigDecimal()
            }
        }
    }
}

// Point SonarQube at the JaCoCo XML report.
sonar {
    properties {
        property(
            "sonar.coverage.jacoco.xmlReportPaths",
            layout.buildDirectory.file("reports/jacoco/test/jacocoTestReport.xml").get().asFile.path,
        )
    }
}

tasks.shadowJar {
    archiveBaseName.set("rapid7-insightidr-mcp")
    archiveClassifier.set("all")
    archiveVersion.set(project.version.toString())
    mergeServiceFiles()
}
